app: 
  port: 6233
  docs: true
  logging: true # for logging stuffs out
  morgan: false # for request logging
  jwt:
    SecretKey: lovemelikeyoudooo
    accessTokenExpiryTime: 7d

database:
  url: mongodb://localhost:27017/default-testDB

docsUrl: "localhost:7000"

# mails:
#   enable: true
#   defaultFrom: miwago@cubettech.com # this is the source email that is used to send emails(from address)
#   admin: 'aumadmin@yopmail.com'
#   errMails: miwago-bug-report@cubettech.com

# issue-maker:
#   service: gitlab
#   projectId: 938
#   endPoint: http://117.247.186.100:9898
#   privateToken: 2zVNcSxwXsLWzHzDudQ1

# frontEnd:
#   web:
#     baseUrl: http://localhost:4200

# AWS_BUCKET_NAME: miwagoassets