# this file is taken only when
# full test is ran, like `npm test`
# ---------------------------------
# created to use withinh development machines
app: 
  docs: false
  logging: true # for logging stuffs out
  morgan: false # for request logging
  
mails:
  enable: false